# Generated by Django 5.2.7 on 2025-10-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_options_remove_customuser_user_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='identity_verified',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_guest',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_host',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='language',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('guest', 'Guest'), ('host', 'Host'), ('both', 'Both Host and Guest')], default='guest', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
