# Generated by Django 6.0.3 on 2026-04-26 14:06

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_verificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='government_id_document',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='government_id_document'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='government_id_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='customuser',
            name='government_id_status',
            field=models.CharField(choices=[('not_submitted', 'Not Submitted'), ('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='not_submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='government_id_type',
            field=models.CharField(blank=True, choices=[('national_id', 'National ID'), ('passport', 'Passport'), ('drivers_license', 'Driver License'), ('alien_id', 'Alien ID')], max_length=30),
        ),
        migrations.AddField(
            model_name='customuser',
            name='government_id_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
