# Generated by Django 5.2.5 on 2025-08-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='baths',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='listing',
            name='beds',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='listing',
            name='property_type',
            field=models.CharField(choices=[('Apartment', 'Apartment'), ('Villa', 'Villa'), ('Loft', 'Loft'), ('Studio', 'Studio'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='sqft',
            field=models.IntegerField(default=500),
        ),
    ]
