# Generated by Django 5.2.5 on 2025-08-09 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0002_listing_baths_listing_beds_listing_property_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='host',
            options={},
        ),
        migrations.AlterModelManagers(
            name='host',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='host',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='host',
            name='email',
        ),
        migrations.RemoveField(
            model_name='host',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='host',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='host',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='host',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='host',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='host',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='host',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='host',
            name='password',
        ),
        migrations.RemoveField(
            model_name='host',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='host',
            name='username',
        ),
        migrations.AddField(
            model_name='host',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='host_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
