# Generated by Django 5.2.7 on 2025-10-25 13:06

import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0006_alter_listing_host'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='host',
            options={'verbose_name': 'Host', 'verbose_name_plural': 'Hosts'},
        ),
        migrations.AddField(
            model_name='host',
            name='account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='host',
            name='address_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='host',
            name='auto_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='host',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='host',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='host',
            name='business_license',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='business_license'),
        ),
        migrations.AddField(
            model_name='host',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='host',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='host',
            name='fully_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='host',
            name='government_id',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='government_id'),
        ),
        migrations.AddField(
            model_name='host',
            name='hosting_since',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='host',
            name='id_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='host',
            name='instant_book',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='host',
            name='is_superhost',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='host',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='host',
            name='response_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='host',
            name='response_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='host',
            name='routing_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='host',
            name='same_day_bookings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='host',
            name='superhost_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='host',
            name='total_bookings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='host',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='host',
            name='total_properties',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='host',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='host_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
