# Generated by Django 5.2.7 on 2025-10-26 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0008_remove_listing_baths_remove_listing_beds_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='review',
            name='property',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.DeleteModel(
            name='ListingImage',
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
