# Generated by Django 6.0.3 on 2026-04-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0009_remove_listing_owner_remove_review_property_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='mpesa_phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='host',
            name='payout_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('bank', 'Bank transfer')], default='mpesa', max_length=20),
        ),
        migrations.AddField(
            model_name='host',
            name='payout_reference_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
