# Generated by Django 5.2.7 on 2025-10-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_bathrooms_property_city_property_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='reviews',
            field=models.FloatField(default=0.0),
        ),
    ]
