# Generated by Django 5.2.7 on 2025-10-25 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_rename_reviews_property_average_rating_review'),
    ]

    operations = [
    ]
