# Generated by Django 5.2.7 on 2025-10-26 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_property'),
        ('properties', '0009_remove_property_owner_listing_alter_review_property_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Property',
        ),
    ]
