# Generated by Django 5.2.7 on 2025-10-26 09:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_property'),
        ('properties', '0010_delete_property'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listing',
            new_name='Property',
        ),
        migrations.RenameModel(
            old_name='ListingImage',
            new_name='PropertyImage',
        ),
    ]
