# Generated by Django 5.2.7 on 2025-10-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_rename_listing_property_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='baths',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='property',
            name='beds',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='price_per_night',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='sqft',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
