# Generated by Django 5.2.7 on 2026-04-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0012_property_baths_property_beds_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="baths",
        ),
        migrations.RemoveField(
            model_name="property",
            name="price",
        ),
        migrations.AlterField(
            model_name="property",
            name="price_per_night",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
