# Generated by Django 5.2.7 on 2026-04-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_alter_propertyimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='policies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='property',
            name='stay_details',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
