# Generated by Django 5.2.7 on 2025-10-26 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_property'),
        ('properties', '0009_remove_property_owner_listing_alter_review_property_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='properties.listing'),
        ),
    ]
